#!/bin/bash

sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot

read -p "Enter fully qualified domain name of your website  " fqdn

certbot -d $fqdn --manual --preferred-challenges dns certonly
